- LICENCE
- README.md
- Added licence text to readme.md
- Added MIT licence file to repo
In line with https://docs.google.com/document/d/1ol86Zvp7DuJ9CYumGC9UisAUUhp4kzwMDEjYKEu_ADo/edit#heading=h.pcmybcsnrr87
> Add license file

- .cfignore
- .gitignore
- Makefile
- config/tech-docs.yml.erb
- manifest.yml.erb
- source/nginx.conf
Added the settings to manually deploy the docs to `docs.notifications.service.gov.uk` for production, or `docs.notify.works` for preview.
> Add the deployment settings

- config/tech-docs.yml.erb
To reduce the size of the left hand nav
> Change heading level from 6 to 2

- source/documentation/_api_keys.md
- source/documentation/_callbacks.md
- source/documentation/_limits.md
- source/documentation/_support.md
- Minor changes to content post Tech Writer 2i review process.
- Added _this_documentation.md file to repo as this should be the first file in the documentation
> Post 2i changes

- source/documentation/_api_keys.md
Add API key instructions to API key section, to address feedback from https://govuk.zendesk.com/agent/tickets/3562076
> Add API key instructions

- Makefile
make generate-manifest doesn't output the data, rather, it just writes
to a file
> use generated manifest in cf-deploy

- .gitignore
- Makefile
- manifest.yml.tpl
call it in the push command instead
> don't use path in manifest.yml, it doesnt work

- config/tech-docs.yml.erb
Copies the same property ID from https://www.notifications.service.gov.uk
> Add Google Analytics to tech docs

- source/documentation/_api_docs.md
> Fix numbered list formatting

- source/documentation/_api_docs.md
This PR corrects inconsistencies in the language and formatting of the reply-to email address section.
> Update reply-to email address section

- source/documentation/_api_docs.md
Also let users know we are open to conversation about enabling
other file types.
> Let users know we also allow CSV files for document upload

- config/tech-docs.yml.erb
New version of https://github.com/alphagov/notifications-tech-docs/pull/105
> Remove Google Analytics tracking code

- source/documentation/_api_docs.md
update with docs as used in other places
> file, not doc

- source/documentation/_api_docs.md
So our docs match our recent change to the API
alphagov/notifications-api#2701
> Update error messages

- source/documentation/_api_docs.md
Updating content so after this change goes live: https://github.com/alphagov/notifications-api/pull/2751 users would know what to expect
> Update REST API documentation to be aware of postcode validation

- source/documentation/_api_docs.md
Equivalent of https://github.com/alphagov/notifications-java-client/pull/180
> Add documentation for is csv flag on send a file by email

- config/tech-docs.yml.erb
- source/accessibility.html.md.erb
Add accessibility statement for Notify tech docs.
> add accessibility statement

- source/documentation/_api_docs.md
Document download will soon support `.rtf` files.
> Update documentation to include rtf files

- Makefile
Note, unlike other apps, our manifest doesn't contain any secret
environment variables. Therefore we don't need to change as much and
don't need to worry about deleting it after use etc.
Also note, have specified `-f` for `cf push` even though `manifest.yml`
is the default argument so just to be extra explicit
> Use cf7 rather than cf6 for cloud foundry commands

- source/documentation/_api_docs.md
See https://github.com/alphagov/notifications-python-client/pull/195
> Add retention for doc download

- source/documentation/_limits.md
See
https://gds.slack.com/archives/CAEHBCNK1/p1712229897350169 for where this was spotted
> Be specific about timezone for midnight when daily limits reset

- source/documentation/client_docs/_node.md
documentation for https://github.com/alphagov/notifications-node-client/pull/200
> documentation for https://github.com/alphagov/notifications-node-client/pull/200

- source/documentation/_api_docs.md
for REST API docs.
Also change values for date fields in those code snippets so they are more illustrative.
> Document new cost data we return for GET notification(s)

- source/documentation/client_docs/_python.md
To match https://github.com/alphagov/notifications-python-client/pull/243
> Update minimum Python version

- source/documentation/client_docs/_node.md
> chore(client_docs): update node client

- openapi/GET_PDF_For_Letter.json
- openapi/GET_received_text_messages.json
- openapi/GET_status_message.json
- openapi/GET_status_messages.json
- openapi/GET_template_by_id.json
- openapi/GET_template_by_id_and_version.json
- openapi/GET_templates.json
- openapi/POST_notification_email.json
- openapi/POST_notification_letter.json
- openapi/POST_notification_sms.json
- openapi/POST_template_preview.json
- openapi/make_request.json
- openapi/publicapi_spec.json
- openapi/redocly.yaml
- openapi/schema.json
- openapi/siteConfig.yaml
- source/documentation/_api_docs.md
Open API Documentation of public API endpoints - more details on [this card](https://trello.com/c/CVxsLVIm/913-open-api-documentation-of-public-api-endpoints)
> Open API Documentation of public API endpoints

- source/documentation/_api_docs.md
- source/documentation/client_docs/_java.md
- source/documentation/client_docs/_net.md
- source/documentation/client_docs/_node.md
- source/documentation/client_docs/_php.md
- source/documentation/client_docs/_python.md
- source/documentation/client_docs/_ruby.md
Added new file types png/jpeg for doc download in 'Send a file' section
> Add new file types png/jpeg for doc download in 'Send a file' section

- source/documentation/client_docs/_python.md
- source/documentation/client_docs/_ruby.md
In this PR I have reviewed all Python docs code snippets.
Work done:
- create an API integration using Notify's Python client and run all the snippets, one by one, to see if they work correctly
- fix any mistakes, add missing fields in Responses
- make Response snippets as lifelike as possible
- make Response snippets consistent - if we use certain values for method args, lets also use them in the Response to show what users can expect
Try to make the snippets consistent with our [Style guide](https://docs.google.com/document/d/1aKIT9YrSGfv30xoytwJQYuPvLSXj-0qnXmE9gXGA3Bo/edit?usp=sharing)
How to review:
Read through the snippets
- do they make sense?
- do they make our docs easier to understand?
After the review of this set of docs, we will work to update all other sets to match (while …
> Review python code snippets

- source/documentation/_api_docs.md
- source/documentation/client_docs/_python.md
best reviewed commit by commit. the second commit was a lot of copy + pasting from the python API docs, the other commits are all cleaning up little bits separate to that
> Rest docs snippets

- openapi/schema.json
- source/documentation/_api_docs.md
- source/documentation/client_docs/_java.md
- source/documentation/client_docs/_net.md
- source/documentation/client_docs/_node.md
- source/documentation/client_docs/_php.md
- source/documentation/client_docs/_ruby.md
- source/documentation/error_tables/_send_a_letter.md
- source/documentation/error_tables/_send_a_precompiled_letter.md
- source/python.html.md.erb
Update all references to postage (including code snippets) to include ‘economy’
> Include economy for postage
