alphagov/notifications-tech-docs

Gemfile
Gemfile.lock
source/documentation/_testing.md

* Fixed internal links by removing the leading `\`
* Pinned the version of the `govuk_tech_docs` gem so that we can be certain about which version is in use.

Minor tweaks

---

app/external_doc.rb
spec/app/external_doc_spec.rb

We now want to display the contents of the `DOCUMENTATION.md` file for each client, instead of the contents of the `README.md` for each client.

Fetch client DOCUMENTATION.md files, not README.md files

---

Makefile
README.md

It is no longer possible to run the app locally with`bundle exec middleman server`
because changes made in https://github.com/alphagov/notifications-tech-docs/pull/7 mean that `tech-docs.yml` either won't exist or may not be up to date.
The new Makefile command to run the app ensures that `tech-docs.yml` is
created and then runs `bundle exec middleman server`.

Add Makefile command to run the app locally

---

Dockerfile
Gemfile
Gemfile.lock
Makefile
script/run_tests.sh

Builds in docker would fail without it because they could not find
a Javascript runtime.
The point of using docker is so that we don't have to install ruby and
its dependencies on our machine.
This commit removes the link between the `cf-deploy` target
and the `generate-build-files` one and instead checks if the build
directory exists before the deployment and removes it in the end to
ensure that we always have a fresh copy of the data.

Add docker

---

Makefile
manifest.yml.tpl

It's simpler and it doesn't require erb to be installed.

Generate manifest using sed

---

config/tech-docs.yml.erb

Changed the Documentation link at the top of the page to link to
https://www.notifications.service.gov.uk/documentation instead of the
homepage of the docs site. Since only the Python docs will be live
initially, we want to carry on linking to the existing documentation
page.

Change link location of 'Documentation' link in header

---

source/documentation/_callbacks.md
source/documentation/_support.md

Having a table followed by a heading was causing the table to be
displayed at the bottom of the page. Adding a sentence below the table
is a quick fix to make the table display in its proper location.

Add sentence below table in callbacks section

---

source/documentation/_limits.md

GOV.UK style is sentence case for headings.

Lowercase heading

---

source/documentation/_limits.md

Central vs local affects the free text message allowance, not the daily limit.

Remove daily limit difference for central/local

---

Gemfile
source/client_template.html.md.erb

Adds support for setting a page’s parent, which means we can highlight ‘Documentation’ in the navigation.
---
Depends on:

Upgrade tech docs Gem to 1.3.0

---

source/documentation/_callbacks.md

- put them above inbound callbacks (normal delivery receipts are the more commonly used feature)
- add the info about the format of inbound callbacks, and associate it with the correct section
- remove redundant line about contacting support if you have any questions (this could apply to any part of the documentation)

Improve documentation about callbacks

---

source/documentation/_limits.md

This commit proposes:
- tidying up the rate limit section so that it’s clearer and less wordy
- front loading the important information (the 3000 messages/min)
- adding some info about rate limits imposed by the phone networks, because people keep asking why their messages have started failing to be delivered

Make rate limits clearer

---

source/documentation/_limits.md

Tech docs Markdown parser seems to require a newline before list.

Fix list syntax

---

Gemfile
Gemfile.lock

We had the `govuk_tech_docs` gem in the Gemfile as
`gem 'govuk_tech_docs', '~> 1.3.1'`. This syntax allowed the minor
version to be increased automatically to version 1.6.0 when the app
was deployed, which caused a breaking change. This commit changes the
Gemfile to pin the minor versions of all the gems to avoid the risk of
any future breaking changes.
(Some of the gems also need upgrading to the latest version, but this is best
done as a separate change.)

Pin gems in the Gemfile more precisely

---

Gemfile
Gemfile.lock

Reverts alphagov/notifications-tech-docs#34
Seems to have broken the thing that highlights the navigation as you scroll the page.

Revert "Bump govuk_tech_docs from 1.3.1 to 1.6.3"

---

source/documentation/_support.md

Updates the link to Slack in the Support section of our Documentation to use the Notify Slack channel's unique ID.
This is needed because the current link uses the channel name, which isn't recognised. Instead of opening the Notify Slack channel, the link defaults to whatever channel the user last had open.

Update link to Slack channel

---

app/external_doc.rb
spec/app/client_docs_spec.rb
spec/app/external_doc_spec.rb
spec/spec_helper.rb

This linter rule is enforced as of https://github.com/alphagov/govuk-lint/pull/124

Use double quotes instead of single quotes in Ruby

---

Makefile

> On Ubuntu, /bin/sh is dash, a shell designed for fast startup and execution with only standard features.
— https://unix.stackexchange.com/a/45784
> The program used as the shell is taken from the variable `SHELL'.  If this variable is not set in your makefile, the program `/bin/sh' is used as the shell.
>
> So put SHELL := /bin/bash at the top of your makefile, and you should be good to go.
— https://stackoverflow.com/a/589300
***
Currently 
```shell
cf v3-apply-manifest notify-tech-docs -f <(make -s generate-manifest)
```
…fails with
```
/bin/sh: 1: Syntax error: "(" unexpected
```

Use bash shell when running commands

---

source/documentation/_api_docs.md

The JWT link was pointing to `https://docs.notifications.service.gov.uk/www.jwt.io` since the `https` wasn't included.

Fix external link

---

source/documentation/_api_docs.md

This PR changes the wording of 2 message status descriptions:
- mentioning the 72 hour period in the _Sending_ status makes it explicit that this a message that remains in this state for longer than a users expects is not 'stuck'
- not mentioning the 72 hour period in the _Phone not accepting messages right now_ status should reduce any confusion for users who see this status after <72 hours
This change was prompted by feedback from a user on x-gov Slack:
>We sent out a message last night and there were a few numbers that did not get it, on checking one, it gives the message: _"The provider could not deliver the message after trying for 72 hours. This can happen when the recipient’s phone is off..."_ Given it is not even 24 hours after the text was sent, any ideas why this report is …

Update status descriptions to help users understand the 72 hour period (REST API)

---

Gemfile
Gemfile.lock
app/client_docs.rb
config.rb
config/tech-docs.yml.erb
source/client_template.html.md.erb
source/rest-api.html.md.erb
spec/app/client_docs_spec.rb

Titles should be unique for accessibility reasons. All of our client docs had the same page title, so this change gives them all different ones.
`full_service_name` in the config has been set to `GOV.UK Notify`. This value gets used at the end of every page title (`| GOV.UK Notify`).
**Rest API title before:**
REST API documentation - GOV.UK Notify | Notify
**Rest API title after:**
REST API documentation | GOV.UK Notify
**Client title before:**
Client documentation - GOV.UK Notify | Notify
**Client title after (using Ruby client as an example):**
Ruby client documentation | GOV.UK Notify

Give each page a unique title

---

source/documentation/_api_docs.md

Also make a sententce about secret key being a part of API key
more explanatory and add a bullet point about API key name.
I am making those changes because we got a query from a user
who did not know what iss is and when I tried to help that user
I realised I do not know what that is either.

Clarify that iss is service id.

---

source/documentation/_api_keys.md

We’re renaming the ‘Team and whitelist’ key in https://github.com/alphagov/notifications-admin/pull/3479
This commit updates the documentation to match.
We will also need to update any references to ‘whitelist’ in the individual clients’ documentation.

Rename whitelist to guest list

---

source/documentation/_api_docs.md

This PR updates the status description tables so that:
* there's a separate table for emails and text messages
* all text message statuses are grouped together
* the `permanent failure` text message status is consistent with the Notify status page
It also replaces the extra status table under 'Get the status of multiple messages' with links to the other status tables.

Update status tables

---

source/documentation/_api_docs.md
source/documentation/_api_keys.md

We missed a few places when renaming 'team and whitelist' to 'team and guest list'.

Make API key names consistent

---

source/documentation/_api_docs.md

The client documentation talks about address lines 1-6 and postcode (including mandatory nature of address lines 1,2 and postcode). Now that we are supporting address lines 1-7 we need to update the documentation to reflect this.
There is a question about what we should say in the docs about the mapping that we do from postcode, or that it is sort of degraded, but needs a bit of a thought for that.
After we have done this story, services will see the new address personalisation that we require and understand that it won’t be a breaking change for them.

Update address fields to include line 7

---

source/documentation/_api_docs.md

Wrong dash meant the bullet points didn't show up properly

Fix personalisation in sending letter section

---

config/tech-docs.yml.erb
source/documentation/_api_docs.md
source/documentation/_api_keys.md
source/documentation/_architecture.md
source/documentation/_callbacks.md
source/documentation/_limits.md
source/documentation/_support.md
source/documentation/_testing.md
source/stylesheets/screen.css.scss

The docs were failing accessibility guidelines because there were multiple H1s on each page. This adjusts the heading levels to correct this.
In order to keep the docs looking the same, we then add our own styles for the table of contents. This is a temporary change until we can make a change to the tech-docs-gem to add these styles for all projects.
_This needs to be deployed at the same time as PRs to adjust the heading levels for all the client docs_

Adjust heading levels while keeping the styling the same

---

source/documentation/_api_docs.md

This PR updates the link and link text so users go to the new 'Letter specification' page, instead of the PDF.
We're doing this because of the work done in: https://github.com/alphagov/notifications-admin/pull/3624
This is part of our accessibility compliance work.

Update link and link text for accessibility

---

source/accessibility.html.md.erb

We have published a new page on Notify with a text version of the letter specification and a link to the PDF version.
We have replaced links to the PDF in the client docs and api docs with a link to this new page.
This means we can remove the PDF issue and any references to it from the documentation accessibility statement.

Remove references to PDF links

---

source/documentation/_callbacks.md

To make it clearer that all of the fields are strings - we had some feedback that this was not clear.

Update callback docs

---

source/accessibility.html.md.erb

We will not be able to fix the accessibility related issues for the tech docs template by the end of 2020.
We are extending the date to end of March 2021. Hopefully by that point we will have some developer resource to look at these issues.

Update Tech Docs Template date to March 2021

---

source/documentation/_callbacks.md

if the service doesnt provide a reference it can be null.
also refer to lack of a value as "null" rather than "nil", as null is what we send in the json, and i have a hot reckon that it's a bit more widely understood than nil.

clarify that reference can be null

---

source/documentation/_api_docs.md

https://www.pivotaltracker.com/story/show/177188288
I've reformatted the list into bullet points, as the letter strings
where becoming hard to decipher. I've also truncated the 'how to fix'
message, so it's more robust against future changes.
The way we expressed formats was inconsistent, so I've added extensions
and grouped them by their colloquial type. Since these are technical
docs, I think we should be specific about the formats we support.

Add excel doc to list of support upload formats

---

source/documentation/_callbacks.md

We now add `template_id` and `template_version` to the delivery status callback (https://github.com/alphagov/notifications-api/pull/3184), so this documents those fields.

Update callbacks section for extra fields

---

source/documentation/_api_docs.md

This is no longer supported [1].
[1]: https://github.com/alphagov/document-download-api/pull/164

Remove Excel doc type from supported list

---

source/documentation/_api_docs.md

If a letter passes our validation but the print provider can not print the letter we should mark it as permanent-failure. An error message for permanent-failure is being added to the UI.
Technical-failure had the wrong message and validation failure will not show the pdf because the letter is in the wrong bucket.

Add permanent-failure status for letters

---

source/documentation/_api_docs.md

Move status descriptions under the two get message methods. Use the same status description for all client docs.

Align status descriptions for all client documentation.

---

source/accessibility.html.md

In April 2020, a DAC audit of GovWifi tech docs found some more accessibility
issues with the tech doc template. The GovWifi team will fix them and push
those fixes upstream but, until then we need to acknowledge them in our
accessibility statement.
These changes could do with some 👀 from @karlchillmaid.
There are 4 WCAG-related issues which must be fixed, and 2 non
WCAG-related issues that should be fixed if time permits.
The 4 WCAG-related issues are as follows:
- In some circumstances, the main page heading is automatically in focus when
the page loads. This means keyboard-only users may miss the navigation
elements. This fails WCAG 2.1 success criterion 2.4.3 - Focus Order.
- The navigation elements are not marked up semantically as hierarchical
headings, which means moving through …

Add template accessibility issues to our statement

---

source/documentation/_api_docs.md

i've added this to the error codes in the "send a file by email" section.
https://docs.notifications.service.gov.uk/rest-api.html#send-a-file-by-email
Should we add it to the letter/sms sections? (initial thought is we don't need to, as a user will have had to go to the "send a file by email" section to learn how to use document download in the first place, and it'll just add clutter, but i can be persuaded)
once we've decided on an approach for this repo i'll copy the resulting PR across to the six clients 😩

add error for when sending documents by sms/email

---

source/documentation/_api_docs.md

Adds a `response` block and an `errors` block for `send an email` section. This is broadly copied from the `send a file by email` block below, with the file-related errors removed.

Add response/error block for send an email

---

source/documentation/_api_docs.md

This PR updates the ‘Send a file by email’ section of the REST-API documentation.
There are 2 stories in the backlog which describe this work:
* [Update 'send a file by email' API client docs for 'email verification' flow](https://www.pivotaltracker.com/story/show/182942256)
* [Update 'send a file by email' API client docs for custom retention periods](https://www.pivotaltracker.com/story/show/182999152)

Add details of ‘confirm email address’ and ‘custom retention period’

---

source/documentation/_api_docs.md

This endpoint is missing from the REST API docs.
---
~I can't get tech-docs to run locally either natively or in docker 🤦~ edit: found a patch that lets me, but we probably need to address this properly when pulling docker images to our cache

Add docs for retrieving a PDF

---

source/documentation/_limits.md

We are changing from an overall daily limit to a per-channel one, to help manage our capacity and plan for future growth.
This commit updates the documentation accordingly.
Need to use HTML here rather than pure Markdown because:
- I don’t think you can put line breaks in table cells
- We need to override the default font-size of `govuk-list` (`19px`) so it matches the rest of the content in the table (`16px`)
***
Depends on:

Add new daily limits

---

config/tech-docs.yml.erb

This PR updates the header links so they match the new GOV.UK Notify navigation:
* Add `Using Notify`
* Remove `Documentation`

Update header links

---

source/documentation/_api_docs.md

This PR updates the ‘Send a file by email’ content to reflect the changes to defaults for:
* email as a password
* retention period
We should merge and deploy this on 12 April.

Update content for launch

---

Gemfile.lock
source/nginx.conf

Ruby has been removed from the cloudfoundry static buildpack, which
means we can't use ERB in the nginx.conf file. This copies the approach
now taken here https://github.com/cloudfoundry/staticfile-buildpack/blob/a30065ddb2f5c439df9abb45309352c248db4ab8/fixtures/reverse_proxy/nginx.conf
There were lots of if statements that I haven't replaced because we
don't have the dotfiles they were checking for. We should look at the
nginx file and app set-up in more detail at some point, but this is a
quick fix to allow the app to be deployed.

Update nginx.conf to remove Ruby

---

source/documentation/_callbacks.md

We receive the occasional zendesk ticket about this and it is nice to include it in our API documentation.
The answer is based on a previous response we've given to a user for this question:
https://ukgovernmentdigital.slack.com/archives/C0E1ADVPC/p1691401900692559?thread_ts=1691401318.326529&cid=C0E1ADVPC
I would like a content designer to review this please as this has been written just by myself with no content designer involved. I wasn't sure on the placement on the content (it could have been higher or lower on the page). Equally, I wasn't sure on the header class. It is an h4 but it could have been an h3 for its own section that would appear in the sidebar.
We could also elaborate on what it means for a request to fail (ie we receive a non 2xx status code response or the request …

Add documentation about callback retry behaviour

---

source/documentation/_api_docs.md

The following sections were missing from the REST API documentation:
- Get a template
- Get a template by ID
- Get a template by ID and version
- Get all templates
- Generate a preview template
- Get received text messages
- Get all received text messages
- Get one page of received text messages
I spotted this when trying to add the latest ‘receive text message’ guidance.

Add missing sections to API guidance

---

manifest.yml.tpl

What
----
Switch to use the PaaS cflinuxfs4 stack.
Why
----
cflinuxfs3 is currently the default on the PaaS. This is based off ubuntu 18.04. This stopped receiving updates after Apr 2023.
cflinuxfs4 will become the default on the PaaS after 27 Nov 2023.
The intention is to migrate all applications to cflinuxfs4 eventually.

Switch to use cflinuxfs4

---

source/documentation/_api_docs.md

Fix quote style to make docs display consistently

---

manifest.yml.tpl

At the moment we aren't specifying, so are only running 1. This is nearly always fine but means if our single instance crashes then we will be serving errors to users.
We have 2 for resiliency.

Run 2 instances always

---

Dockerfile

The image was pulling from gchr which was the wrong platform for ruby

use ruby-bookwork armv8

---

source/documentation/_api_docs.md

Add the guidance into the existing code examples, like:

Guidance for personalised bullet points in personalisation

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

Updates the REST and client docs to describe the new 'custom filename' feature for sending files by email.

Allow setting custom filenames for documents

---

source/documentation/client_docs/_java.md
source/documentation/client_docs/_php.md

It got lost while moving the docs over. I checked and nothing else is missing (I compared latest `DOCUMENTATION.md` from php-client with `_php.md` from tech-docs repo)
Also add java notations to code snippets in java docs where it was missing.

Add missing bullet points guidance to PHP docs

---

source/documentation/_api_docs.md

Add missing include_jobs argument to REST API docs

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

The status code that gets returned when sending letters with a team API key is `403` and not `400`.
(https://github.com/alphagov/notifications-api/blob/05b7ae9ddd33d1c426fa387b998448915eeecd88/app/v2/notifications/post_notifications.py#L361)

Fix status code for sending letters with a team key

---

source/documentation/_api_docs.md

The URI documented for getting a preview of a template had "templates" incorrectly pluralised when it should be "template".

Correct URI for "Generate a preview template"

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

This PR updates all our API client documents and the generic API document to detail the addition of the `one_click_unsubscribe_url` parameter.

One click unsubscribe url

---

source/documentation/client_docs/_php.md

None of the other clients have this header at the start of their ‘Send a letter‘ sections
Compare before:
PHP | Python
---|---

Remove redundant header from send letter section of PHP docs

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

We always say emails, text messages and letters, in that order.
We don’t talk about ‘documents’ as part of the high-level product proposition.

Make proposition line consistent across docs

---

source/documentation/client_docs/_python.md

- additional fields were added to get notification endpoint [as part of this PR](https://github.com/alphagov/notifications-api/pull/4105) in our public API
- this PR updates the documentation details for our python client
[Add GET notification cost data to API clients and API client docs](https://trello.com/c/5VZrBNpU/845-3-add-get-notification-cost-data-to-api-clients-and-api-client-docs)

chore(python-docs): update documentation for python client

---

source/documentation/_support.md
source/java.html.md.erb
source/net.html.md.erb
source/node.html.md.erb
source/php.html.md.erb
source/python.html.md.erb
source/rest-api.html.md.erb
source/ruby.html.md.erb

See discussion at: https://github.com/alphagov/notifications-tech-docs/pull/227#pullrequestreview-2101567237
David said:
> Controversially, I think we should get rid of this whole support section...
>
> The reason is that there is already a link at the top of the page which says 'support' and if you click on that it takes you to all this information already. Then it means we only have one place to keep up to date and consistent.
>
> My guess would be not many people would scroll down here to find information about support, when they will probably instead see 'support' at the top right too
Karl said:
> I agree.
>
> I was reminded that the Support link appears at the top of the docs when discussing an unrelated issue with Tom yesterday.
Closes #227

Remove support section from documentation

---

source/documentation/_api_docs.md

All of our clients have a ‘Setting up the client’ section which includes subsections about installing dependencies, API keys, etc.
In the REST API documentation that information is at a level above, not within its own section.
This commit makes the REST API documentation consistent with the other clients, which should make it easier to navigate.
Before | After 
---|---

Add a setup section to the REST API documentation

---

source/documentation/client_docs/_java.md

chore: update java docs to include new notification fields (cost_in_pounds, is_data_ready and cost_details)

---

source/documentation/client_docs/_ruby.md

chore: update ruby client with new fields for cost_in_pounds, is_cost_data_ready and cost_details

---

source/documentation/client_docs/_php.md

chore: php client include new notification fields (cost_in_pounds, is_data_ready and cost_details

---

source/documentation/client_docs/_ruby.md

- removing mention of scheduled_for field from docs as we do not return this on get_notification(id)

chore: remove scheduled for field as it is not returned on ruby client

---

source/documentation/client_docs/_net.md

chore: update net docs to include new notification fields (cost_in_pounds, is_data_ready and cost_details) response

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

Updated to add unsubscribe links markdown at the bottom of subscription emails.
User will need to add this with the one-click unsubscribe in the header of emails in API.

One click unsub update

---

source/accessibility.html.md

Updates the accessibility statement so that it reflects the accessibility status of the tech docs against WCAG 2.2.
This considers changes to [the sample accessibility statement on the service manual](https://www.gov.uk/government/publications/sample-accessibility-statement/sample-accessibility-statement-for-a-fictional-public-sector-website) and work done on the tech docs gem for WCAG 2.2 compliance which produced the following issues:
- [table of contents marked as a dialog when it isn't](https://github.com/alphagov/tech-docs-gem/issues?q=is%3Aissue+is%3Aclosed)
- [focused links can be covered by the table of contents button](https://github.com/alphagov/tech-docs-gem/issues/356)
- [images with blank alt text shouldn't be links](https://github.com/alphagov/tech-docs-gem/issues/355)

Update accessibility statement for WCAG 2.2

---

source/documentation/_api_docs.md
source/documentation/_api_keys.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

Checked and updated links in the doc:
- styling for external links (removed [external link] as not consistent with design system)
- updated link to trial mode page in the error codes

Update links and styling of links in the API docs

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

Links to the 'Ask a question or give feedback' updated to the 'Contact support' page

Support page link in api consistency

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

Updated headings to align across API docs (including missing headings, inconsistently named headings)
Also update the one click unsubscribe argument - it said it's required previously, but the send_email request will succeed without it. So we say it's recommended now.

Update one click unsubscribe argument from required to recommended and update some headings

---

source/documentation/client_docs/_php.md

First example in the PHP docs is missing language-specific syntax highlighting

Add missing syntax highlighting

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

Re-drafted guidance on adding a one click unsubscribe link in the email body - basic guidance on what to do.

One click unsubscribe guidance re-draft

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md

It turns out that for service's retention period applies when querying for notifications status of multile messages and not 7 days as we state. User raised this
Omitted python and ruby as fixes for that are in #264

Clarify returned data time span for multiple messages statuses

---

source/documentation/client_docs/_node.md

- Used as reference Python docs to make changes to wording and content
- Refactored single quotes to double quotes throughout the documentation to ensure consistency
- Added `Get all received text messages` section which was missing: Python and Node retrieve this messages differently but it is still important to provide this information clearly.
- Refactored code snippets to include `var` and semicolon at the end of expressions
[Client Doc (Node) - Update code snippets](https://trello.com/c/iOmmzTvG/1107-client-doc-node-update-code-snippets)

chore: Update Client Node Documentation

---

source/documentation/client_docs/_node.md

- Due to lack of space in between the "For example" text and the "let phoneNumber..."  code snippet, the formatting of the code was not properly applied in the documentation

fix: Node client phone number snippet

---

Makefile

Docker defaults to using `0.0.0.0`, the default route listening on all
network interfaces, as opposed to the loopback address (`127.0.0.1`).
This has security implications and we have been asked to change it.
We made this change for all other apps last year, (for example
https://github.com/alphagov/notifications-antivirus/pull/170) but forgot this one.

Change port mapping to use the loopback address

---

source/documentation/_callbacks.md

This PR is a draft documentation of the proposed API callback for returned letters as described in this [card](https://trello.com/c/MqwEyn03/155-write-draft-documentation-for-api-callbacks-for-returned-letters)

Add returned letters callback

---

source/documentation/_api_docs.md
source/documentation/client_docs/_java.md
source/documentation/client_docs/_net.md
source/documentation/client_docs/_node.md
source/documentation/client_docs/_php.md
source/documentation/client_docs/_python.md
source/documentation/client_docs/_ruby.md

This PR adds a section on placeholder injection to the tech docs as described in [this](https://trello.com/c/b1CpDIxu/238-add-a-section-to-our-tech-docs-about-how-to-handle-user-input) card.
The aim is to explain what the issue is and offer a means of mitigation. The team is working on deploying a solution on our end in the not to distant future.

Add placeholder injection guidance

---

Gemfile
Gemfile.lock

[Fixes favicon issue from v4.3.0](https://github.com/alphagov/tech-docs-gem/pull/391)

Bump tech docs gem to latest v4.3.1

---

source/documentation/_limits.md

Update daily text message limits to include 100 default international text message

Update daily text message limits to include default international text message limit

---

source/documentation/client_docs/_net.md

We released version 4.0.0 in 2021 so enough time should now have passed that we don’t need to tell people how to get older versions than that

Remove warning about installing older versions of .NET client

---

Gemfile
Gemfile.lock

Release v5.0.2 - https://github.com/alphagov/tech-docs-gem/releases/tag/v5.0.2 - enables rebrand for a site that uses the crown
Trello ticket: https://trello.com/c/eIepj4vM/1346-turn-on-new-govuk-brand-in-our-web-apps-and-the-email-template

[DO NOT MERGE UNTIL 25 JUNE] Upgrade gem to v5 to enable rebrand

---

source/java.html.md.erb
source/rest-api.html.md.erb

We missed economy mail from:
* the REST API documentation
* the Java client documentation
This PR adds that content in the same format is it appears in the other API client docs.

Add economy mail

---

source/documentation/error_tables/_generate_a_preview_template.md
source/documentation/error_tables/_generic_errors.md
source/documentation/error_tables/_get_a_page_of_received_text_messages.md
source/documentation/error_tables/_get_a_pdf_for_a_letter_notification.md
source/documentation/error_tables/_get_a_template_by_id.md
source/documentation/error_tables/_get_a_template_by_id_and_version.md
source/documentation/error_tables/_get_the_status_of_multiple_messages.md
source/documentation/error_tables/_get_the_status_of_one_message.md
source/documentation/error_tables/_send_a_file_by_email.md
source/documentation/error_tables/_send_a_letter.md
source/documentation/error_tables/_send_a_precompiled_letter.md
source/documentation/error_tables/_send_a_text_message.md
source/documentation/error_tables/_send_an_email.md
source/documentation/error_tables/ruby/_generate_a_preview_template.md
source/documentation/error_tables/ruby/_generic_errors.md
source/documentation/error_tables/ruby/_get_a_page_of_received_text_messages.md
source/documentation/error_tables/ruby/_get_a_pdf_for_a_letter_notification.md
source/documentation/error_tables/ruby/_get_a_template_by_id.md
source/documentation/error_tables/ruby/_get_a_template_by_id_and_version.md
source/documentation/error_tables/ruby/_get_all_templates.md
source/documentation/error_tables/ruby/_get_the_status_of_multiple_messages.md
source/documentation/error_tables/ruby/_get_the_status_of_one_message.md
source/documentation/error_tables/ruby/_send_a_file_by_email.md
source/documentation/error_tables/ruby/_send_a_letter.md
source/documentation/error_tables/ruby/_send_a_precompiled_letter.md
source/documentation/error_tables/ruby/_send_a_text_message.md
source/documentation/error_tables/ruby/_send_an_email.md

Add schema validation errors sub-section to all the tech docs to show service users example schema validation errors they may see when interacting with our API.
Also link from all error sections that mention schema validation errors to this new schema validation errors sub-section.
1. Look the code over - easier when done commit by commit.
2. Run the app locally and check if everything looks as expected.

Add schema validation errors sub-section to all the tech docs

---

source/documentation/_limits.md

Added content for the token bucket algorithm advising users to avoid sending messages in a large spike

Rate limit - token bucket algorithm 
